version: '3'

services:

  postgres:
    image: postgres:9
    env_file:
      - '.env'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - '.env'
    ports:
      - '8081:80'

  dataton:
    build: .
    depends_on:
      - postgres
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "dataton_anticorrupcion.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - .:/app
    ports:
      - '8001:8000'

volumes:
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/estigia/Docker/Dataton/postgres'
